CREATE TABLE EMPRESA_CONTRATANTE (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo INT NOT NULL,
    nome VARCHAR(160) NOT NULL,
    cnpj VARCHAR(14),
    email VARCHAR(255),
    telefone VARCHAR(40),
    uf VARCHAR(2),
    ativo BOOLEAN NOT NULL,
    fornecedor_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(120) NOT NULL,
    updated_by VARCHAR(120) NOT NULL,
    CONSTRAINT pk_empresa_contratante PRIMARY KEY (id),
    CONSTRAINT uk_empresa_contratante_codigo UNIQUE (codigo),
    CONSTRAINT uk_empresa_contratante_fornecedor UNIQUE (fornecedor_id),
    CONSTRAINT fk_empresa_contratante_fornecedor
        FOREIGN KEY (fornecedor_id) REFERENCES fornecedor(id)
);

