CREATE TABLE FORNECEDOR (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(120) NOT NULL,
    ativo BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(120) NOT NULL,
    updated_by VARCHAR(120) NOT NULL,
    CONSTRAINT pk_fornecedor PRIMARY KEY (id),
    CONSTRAINT uk_fornecedor_nome UNIQUE (nome)
);

INSERT INTO FORNECEDOR (nome, ativo, created_at, updated_at, created_by, updated_by)
VALUES ('Fornecedor nao informado', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'flyway', 'flyway');

INSERT INTO FORNECEDOR (nome, ativo, created_at, updated_at, created_by, updated_by)
SELECT DISTINCT
    CONCAT('Fornecedor ', CAST(empresa_id AS VARCHAR)),
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'flyway',
    'flyway'
FROM PROMOTOR
WHERE empresa_id IS NOT NULL;

ALTER TABLE PROMOTOR ADD COLUMN fornecedor_id INTEGER;

UPDATE PROMOTOR p
SET fornecedor_id = COALESCE(
    (SELECT f.id FROM FORNECEDOR f WHERE f.nome = CONCAT('Fornecedor ', CAST(p.empresa_id AS VARCHAR))),
    (SELECT f2.id FROM FORNECEDOR f2 WHERE f2.nome = 'Fornecedor nao informado')
);

ALTER TABLE PROMOTOR ALTER COLUMN fornecedor_id SET NOT NULL;
ALTER TABLE PROMOTOR ADD CONSTRAINT fk_promotor_fornecedor
    FOREIGN KEY (fornecedor_id) REFERENCES FORNECEDOR (id);
ALTER TABLE PROMOTOR DROP COLUMN empresa_id;
