CREATE TABLE CONFIGURACAO_EMPRESA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    empresa_id INTEGER NOT NULL,
    encerramento_automatico_habilitado BOOLEAN NOT NULL,
    horario_encerramento_automatico TIME,
    texto_observacao_encerramento_automatico VARCHAR(255),
    permitir_multiplas_entradas_no_dia BOOLEAN NOT NULL,
    exigir_foto_na_entrada BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(120) NOT NULL,
    updated_by VARCHAR(120) NOT NULL,
    CONSTRAINT pk_configuracao_empresa PRIMARY KEY (id),
    CONSTRAINT uk_configuracao_empresa_empresa UNIQUE (empresa_id),
    CONSTRAINT fk_configuracao_empresa_fornecedor FOREIGN KEY (empresa_id) REFERENCES FORNECEDOR (id) ON DELETE CASCADE
);

INSERT INTO CONFIGURACAO_EMPRESA (
    empresa_id,
    encerramento_automatico_habilitado,
    horario_encerramento_automatico,
    texto_observacao_encerramento_automatico,
    permitir_multiplas_entradas_no_dia,
    exigir_foto_na_entrada,
    created_at,
    updated_at,
    created_by,
    updated_by
)
SELECT
    f.id,
    FALSE,
    TIME '22:00:00',
    'Encerramento automatico realizado pelo sistema.',
    TRUE,
    FALSE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'flyway',
    'flyway'
FROM FORNECEDOR f
WHERE NOT EXISTS (
    SELECT 1
    FROM CONFIGURACAO_EMPRESA c
    WHERE c.empresa_id = f.id
);
